import { useEffect } from "react";
import "../styles/Main.scss";
import Head from "next/head";
import { DefaultSeo } from "next-seo";
import { AnimatePresence } from "framer-motion";
import type { AppProps } from "next/app";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function App({ Component, pageProps }: AppProps) {
  /* useEffect(() => {
    if (window.performance) {
      if (performance.navigation.type == 1) {
        window.location.href = "/";
      }
    }
  }, []); */
  return (
    <>
      <Head>
        <title>Viktor Bilokapić</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/tiny-slider.css"
        />
      </Head>
      <DefaultSeo
        titleTemplate="%s - Viktor Bilokapić"
        openGraph={{
          type: "website",
          locale: "en_IE",
          description: "The personal website for Viktor Bilokapić, developer.",
          site_name: "Viktor Bilokapić | viktor.dev",
          images: [],
        }}
      />
      <AnimatePresence exitBeforeEnter>
        <main>
          <div className="main-wrapper">
            <Navbar />
            <Component {...pageProps} />
            <Footer />
          </div>
        </main>
      </AnimatePresence>
    </>
  );
}
